src/components/Cards/EditProfile/EditProfile.tsx, src/components/ProfilePage/ProfilePage.tsx
FIXED::feat: Implement Profile Editing Feature #50
#50
- Image Upload Paths:
Updated banner image path to user-banners/user-banner-${uid} to ensure overwriting existing images.
- Data Fetching:
Added fetchUserData function to populate user's existing data when the modal is shown.
- Form Input Handlers:
Added handleImageUpload for image selection.
Added handleTagChange to limit tags to a maximum of 5.
- Submit Logic:
**Modified handleSubmit to:**
Upload images and retrieve URLs.
Save updated user details to Firebase.
Display success and error toasts.
Refresh page on success.
User Feedback:
- Added loading state to disable "Save Changes" button during updates.
Integrated react-toastify for success and error notifications.
https://github.com/Tanay-ErrorCode/lupo-skill/assets/101548649/da61a0b …
=> FIXED::feat: Implement Profile Editing Feature #50

src/components/Cards/EditProfile/EditProfile.tsx
Fixed:FIXED::bug : Allowing All File Types for Upload in Edit Profile Popup #79
#79
-Added accept="image/*"
-Added a condition if file startswith (image/)
=> FIXED::bug : Allowing All File Types for Upload in Edit Profile Popup #79

src/App.css
A bugfix, fixed overlapping of the navbar
41
Fixes #
I added  a CSS property to fix the overlapping of  the nav bar
=> Fixed the overlapping of Navbar

package-lock.json, package.json, src/components/Cards/CreateEvent/CreateEvent.tsx, src/components/Cards/EditProfile/EditProfile.tsx, src/firebaseConf.ts, src/utils/ImageCropper.tsx
Fixed::feat: Image Compression before upload #96
#96
-modified image cropper to accept aspect ratio as prop;
-add a function to compress-cropped image and then store it in database
https://github.com/Tanay-ErrorCode/lupo-skill/assets/101548649/2846d2a2-f561-48d2-83ba-a643ed0bee34
=> Fixed::feat: Image Compression before upload #96

src/components/Cards/CreateEvent/CreateEvent.css
Changed the font color to black for "Create Event" text on create event card
Fixes #
#109
=> #109 Bug fixed  :  Unreadable text on create event page 

src/components/HomePage/HomePage.tsx
FIXED::bug : 'Continue With Google' Button Visible on Home Screen Even When Signed In #112
#112
Added a conditon if localstorage have uid then dont show button else google button will be displayed
=> FIXED::bug : 'Continue With Google' Button Visible on Home Screen Even When Signed In #112

src/components/Cards/EditProfile/EditProfile.tsx, src/firebaseConf.ts
Fixed::bug : Profile image on navbar persists after changing profile picture #117
-added a logic when user updates profile pic the image url should get store in local storage.
#117
=> Fixed::bug : Profile image on navbar persists after changing profile picture #117

src/components/Signup/Signup.tsx
Fixed::bug : Google profile image displays on LogIn even if it is updated in database #123
-just updated logic of signup page if snnapshot.exist() it should store pic url present in rtdb to local storage
=> FIXED::bug : Google profile image displays on LogIn even if it is updated in database #123

src/components/Cards/EventCard/EventCard.tsx
initially it was comparing only dates not time so, it was creating ambiguity for buttons to show either expired or register so in this PR i have also compared the time along with date , for that i formatted date and time combined in single variable and kept according to new Date() format to compare with it 
Fixes #99 
=> bug : fixing event date

package-lock.json, package.json, src/components/HomePage/HomePage.tsx, src/firebaseConf.ts
I have implemented scroll animations on the website (only homepage as you suggested). The "framer-motion" library was utilized for the animation functionality. Please review the changes and consider merging them for GSSOC'24.
Fixes #100 
https://github.com/Tanay-ErrorCode/lupo-skill/assets/132138302/4203b984-2c6b-4349-8bfa-6f0ff2fb47c7
=> Smooth scroll animations added.

src/components/HomePage/HomePage.tsx
feat: Add animation to the testimonials section. #142
ADDED ANIMATION TO TESTIMONIAL SECTION
#142
=> feat: Add animation to the testimonials section. #142

src/components/Signup/Signup.tsx
Signup with gooogle to Login with Google
Fixes #138 
=> Signup with gooogle to Login with Google

src/App.tsx, src/components/Cards/EventCard/EventCard.tsx, src/components/DashBoard/DashBoard.tsx, src/components/EventDetails/EventDetails.tsx, src/components/ProfilePage/ProfilePage.tsx, src/components/Signup/Signup.tsx, src/utils/PageTitle.tsx
feat: Improve Page Title Handling #44
- created pagetitle.tsx in Utils so that page title can be added easily
https://github.com/Tanay-ErrorCode/lupo-skill/assets/101548649/1ba50b84-a445-4dee-a863-061a51c7a808
#44
=> feat: Improve Page Title Handling #44

src/components/Cards/EditProfile/EditProfile.tsx, src/firebaseConf.ts
FIXED::bug : Users Can Edit Name in Profile Edit Section #153
-disabled that field so user cant edit it
#153
=> FIXED::bug : Users Can Edit Name in Profile Edit Section #153

src/components/DashBoard/DashBoard.tsx
Fixed::bug : SignUp/LogIn Popup and Toast Displayed When User is Logged Out. #165
-removed toast
#165
=> Fixed::bug : SignUp/LogIn Popup and Toast Displayed When User is Logged Out. #165

package-lock.json, src/App.css, src/App.tsx, src/components/Cards/CreateEvent/CreateEvent.tsx, src/components/Cards/EditEventModal/EditEventModal.tsx, src/components/Cards/EditProfile/EditProfile.tsx, src/components/Signup/Signup.tsx
feat: Add animation to all the modals #164
-Added Modal Animation in app.css
#164
=> feat: Add animation to all the modals #164added animation to modals

src/components/Cards/EventCard/EventCard.css, src/components/Cards/EventCard/EventCard.tsx
feat: Their should be option to delete created event by user. #167
-ADDED cancelregistration function in event cards page
#168 
https://github.com/Tanay-ErrorCode/lupo-skill/assets/101548649/09a963db-8254-44f9-a991-173ad46a08e1
=> feat: Option to remove registration of registered event. #168

src/components/Cards/EventCard/EventCard.tsx, src/components/ProfilePage/ProfilePage.tsx
feat: Their should be option to delete created event by user. #167
-Add DELETE Functionality
#167
=> feat: Their should be option to delete created event by user. #167

src/components/HomePage/HomePage.tsx
bug: Text does not disappear on sign-in #194
=> bug: Text does not disappear on sign-in #194

package-lock.json, package.json, src/components/Cards/EditProfile/EditProfile.tsx, src/components/HomePage/HomePage.tsx, src/components/ProfilePage/ProfilePage.tsx
Reverts Tanay-ErrorCode/lupo-skill#120
=> Revert "Added social media field and improved the validity of social media url."

src/components/testimonial/testimonial.css
bug : Hover Issue ON carousel Card item #208
-Fixed  bug
**#208**
=> bug : Hover Issue ON carousel Card item #208

src/components/ProfilePage/ProfilePage.tsx, src/utils/InputLink.tsx
feat: Update Social Media Links Display Logic on Profile #211
#211
=> feat: Update Social Media Links Display Logic on Profile #211

src/App.tsx, src/components/Cards/CreateEvent/CreateEvent.tsx, src/components/NavBar/NavBar.tsx
Feature - Just a conversion of  a modal to a stand alone page for creating a event.
Fixes #198
Made changes to app.tsx, navbar.tsx and createEvent.tsx files.
=> Implemented modal to a page

src/components/EventDetails/EventDetails.css, src/components/EventDetails/EventDetails.tsx, src/firebaseConf.ts
Added margin So it will work fine now
#182
=> bug : Navbar Overlapping Event Details Card #182

src/components/NavBar/NavBar.tsx, src/components/Notification/NotificationsPanel.tsx, src/firebaseConf.ts
feat: Implement UI for In-App Notifications #206
-Added Icon and dummy data for Now
#206
Fixes #206
=> feat: Implement UI for In-App Notifications #206

src/index.css
Hey @Tanay-ErrorCode 
I have added "Style the Vertical Scrollbar" Matching to "Website Design" theme and as you said similar to firefox default scrollbar specially hover effect.
Fixes #238 
https://github.com/Tanay-ErrorCode/lupo-skill/assets/101971980/9880b5f0-6c79-4a22-8ab9-d69d89ccf773
Please take a look and review it thank you!
=> "Styled the Vertical Scrollbar" Matching to "Website Design" theme

src/index.css
Reverts Tanay-ErrorCode/lupo-skill#243
=> Revert ""Styled the Vertical Scrollbar" Matching to "Website Design" theme"

LEARN.md, src/components/HomePage/HomePage.tsx
**Background image fixed for smaller-device**
**Fixes** #232 
=> Background image fixed for smaller-device

LEARN.md, src/components/HomePage/HomePage.tsx
Reverts Tanay-ErrorCode/lupo-skill#249
=> Revert "Background image fixed for smaller-device"

src/components/Footer/Footer.css, src/components/Footer/Footer.tsx, src/components/HomePage/HomePage.tsx
1. Added youtube link and icon in the footer 
2. Reduced the height of the footer
3. Checked responsiveness
Fixes #246 
responsive:
=> Enhanced footer 

src/components/HomePage/HomePage.tsx
Removed the white space above main heading for better visibility
Fixes #244 
before:
after:
=> Removed white spaces

src/components/Footer/Footer.css, src/components/Footer/Footer.tsx, src/components/HomePage/HomePage.tsx
Reverts Tanay-ErrorCode/lupo-skill#254
=> Revert "Enhanced footer "

package-lock.json, package.json, src/App.tsx, src/components/Article/ArticlePage.css, src/components/Article/ArticlePage.tsx, src/components/Article/ArticleWritingPage.tsx, src/components/Article/ArticlesHomepage.css, src/components/Article/ArticlesHomepage.tsx, src/components/NavBar/NavBar.tsx
feat: Add support for article writing (backend) #261
#261 
-Added Backend Codes
Fixes #
https://github.com/Tanay-ErrorCode/lupo-skill/assets/101548649/a26a4bf0-21ed-4611-8bec-e50c48318a57
=> feat: Add support for article writing (backend) #261

src/components/Article/ArticlePage.css
bug : Image overflowing the the article #286 
fixed image overflowing bug
#286 
Fixes  #286 
before::
After:;
=> bug : Image overflowing the the article #286

src/components/Article/ArticlePage.tsx
feat: Dynamic title display on article reading page #285
#285 
Fixes #285 
=> feat: Dynamic title display on article reading page #285

src/components/Article/ArticlePage.tsx, src/components/Article/ArticlesHomepage.css, src/components/Article/ArticlesHomepage.tsx
=> feat: Opening writer profile from the article reading page. #287

src/components/Cards/CreateEvent/CreateEvent.tsx, src/components/NavBar/NavBar.tsx
FIXED:bug : If User is Not Logged In Then Signup Model should comeup in Create Event #300
#300 
Fixes #300 
Uploading tanayArticleBugFixed.mp4…
=> bug : If User is Not Logged In Then Signup Model should comeup in Create Event #300

src/components/Article/ArticlesHomepage.tsx, src/firebaseConf.ts
Now by clicking anywhere on the text the article would open in full view addressing issue #302
Fixes #302 
https://github.com/Tanay-ErrorCode/lupo-skill/assets/32425567/4ec6e059-0ddd-4e66-9192-dcfb5d335c9b
=> Added:Click any where on the text box

src/components/HomePage/HomePage.css, src/components/HomePage/HomePage.tsx, src/firebaseConf.ts
feature: Enhanced the ui of the 'Explore Learning Opportunities' section in home.
**Issue Number:** 
Fixes #236 
https://github.com/Tanay-ErrorCode/lupo-skill/assets/139672976/ddec87dc-254b-46d5-b8ae-3fb824e87f31
=> Improve the ui of the 'Explore Learning Opportunities' section in home

src/components/Article/ArticlePage.tsx, src/components/Article/ArticlesHomepage.tsx, src/components/NavBar/NavBar.tsx
Now users can access all articles without being logged in.
**Issue Number:**  319
Fixes #319 
https://github.com/Tanay-ErrorCode/lupo-skill/assets/83805376/5a8a5d9d-857c-4693-8e68-12e9f4e35bd7
Also added a toast telling users to login to view an article or to create an article
=> Articles can we viewed without SignUp

src/components/ProfilePage/ProfilePage.tsx
Removed pagination for no content
Fixes #330
=> Fix for issue #330 : Removed unnecessary pagination

src/components/EventDetails/EventDetails.css, src/components/EventDetails/EventDetails.tsx, src/firebaseConf.ts
-Added option to share Event in Event-details page 
#318 
Fixes #318 
=> feat: Add option to share event #318

src/components/EventDetails/EventDetails.css
=> bug : Every line in article content is truncated #337

src/components/Article/ArticlePage.css, src/components/Article/ArticlePage.tsx
-Added option to share Article in article.tsx page
Fixes #336 
=> feat: Share option for articles. #336

src/App.tsx, src/components/Article/ArticleEditingPage.tsx, src/components/Article/ArticlePage.tsx, src/components/Article/ArticleWritingPage.tsx
closes #324 
-updated ArticleWriting page to handle update as well
Fixes #
https://github.com/Tanay-ErrorCode/lupo-skill/assets/101548649/07f739eb-c1e5-463b-92b7-e5e8002df30a
=> feat: Add edit article feature #324

src/components/EventList/EventList.tsx
Added framer motion
Fixes #282
https://github.com/user-attachments/assets/9b3ac3b7-c494-4d20-885b-a8996fba01f4
its much better in website (framedrops in video)
=> feat: Adding Loader and Animation to the event cards #282

src/components/Cards/CreateEvent/CreateEvent.tsx, src/components/Cards/EventCard/EventCard.tsx
feat: Add Preview Functionality to Event Creation Page #353
hey In This I  Used Modal That Was there For Cropping
Fixes #353 
=> feat: Add Preview Functionality to Event Creation Page #353

src/components/Article/ArticleWritingPage.tsx, src/components/Cards/CreateEvent/CreateEvent.tsx, src/components/NavBar/NavBar.tsx, src/utils/useNavigationPrompt.tsx
working fine
Fixes #352 
https://github.com/user-attachments/assets/36c89535-3910-412a-bd9b-92c3c09cc011
=> feat: Alert on unpublished events, articles. #352

src/components/Cards/EditEventModal/EditEventModal.tsx, src/components/Cards/EventCard/EventCard.tsx, src/components/Notification/NotificationsPanel.tsx
Implement backend for notifications
#363 
Fixes #363 
https://github.com/user-attachments/assets/0a81908a-977d-49de-9048-531985379d6e
=> feat: Implement backend for notifications #363

src/App.tsx, src/components/Meetings/MeetingPage.css, src/components/Meetings/MeetingPage.tsx
=> feat: Develop live event WebRTC interface. #358

src/components/Article/ArticlePage.tsx, src/components/Article/ArticlesHomepage.tsx, src/components/Article/Discussion.css, src/components/Article/DiscussionModal.tsx
=> feat: want to write backend Of comment section of blogs page #369

src/components/ProfilePage/ProfilePage.css, src/components/ProfilePage/ProfilePage.tsx
=> eat: Add created articles in the profile page. #384

src/components/Article/ArticlePage.tsx, src/components/Article/DiscussionModal.tsx, src/components/Signup/Signup.tsx
Fixed 
Fixes #388 
https://github.com/user-attachments/assets/bdf4ecdd-9fa3-4831-b449-102e828251fe
=> bug : Prevent reading data from server frequently #388

src/components/Article/ArticlePage.tsx, src/components/Article/DiscussionModal.tsx
Fixes #392 
https://github.com/user-attachments/assets/7b86209b-5b57-41f0-8a02-455df5a09e80
=> feat: Comment button click behavior #392

src/components/Cards/CreateEvent/CreateEvent.tsx, src/components/EventDetails/EventDetails.tsx, src/utils/FileDropZone.tsx
#397 
Fixes #397 
https://github.com/user-attachments/assets/64ce014f-9b80-42dd-95a7-ca6496ad819b
=> feat: File add support for events. #397

src/components/Cards/CreateEvent/CreateEvent.tsx
=> bug : Can create events before current time. #403

src/components/Cards/CreateEvent/CreateEvent.tsx, src/components/NavBar/NavBar.tsx
Fixes #404 
https://github.com/user-attachments/assets/6b19d73a-6e56-41e0-b373-ff5850c8d1a5
=> bug : Can't access any page without login #404

src/components/Cards/CreateEvent/CreateEvent.tsx, src/components/EventList/EventList.css, src/components/EventList/EventList.tsx, src/components/NavBar/NavBar.tsx
=> bug : Move "Create Event" Button from Navbar to Events Page #407

src/components/Cards/CreateEvent/CreateEvent.tsx, src/components/EventList/EventList.css, src/components/EventList/EventList.tsx, src/components/NavBar/NavBar.tsx
Fixes #409 
https://github.com/user-attachments/assets/c79a1737-6b49-494a-8e7d-5f7651d37320
=> Make Navbar Logo and Name Clickable to Redirect to Homepage #409
